services:
  kafka:
    image: confluentinc/cp-kafka:7.8.3
    container_name: kafka
    ports:
      - "9092:9092"

    environment:
      KAFKA_KRAFT_MODE: 'true'

      CLUSTER_ID: '1L6g7nGhU-eAKfL--X25wo'
      KAFKA_NODE_ID: 1

      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs

    volumes:
      - kafka_kraft:/var/lib/kafka/data

  mysql: 
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
    - mysqlvol:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_USER: kobi
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: targets_bank 

  phpmyadmin:
    image: phpmyadmin
    ports: 
    - 8080:80
    restart: always
    links: 
    - mysql
    environment:
      PMA_ARBITRARY: 1
    depends_on:
      - mysql

  targets_bank:
    build: targets_bank
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_PASSWORD: pass
      MYSQL_USER: kobi
      MYSQL_DATABASE: targets_bank
    depends_on:
      - mysql
  intel:
    build: intel
    environment:
      KAFKA_HOST: kafka
      KAFKA_PORT: 3306
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_PASSWORD: pass
      MYSQL_USER: kobi
      MYSQL_DATABASE: targets_bank
    depends_on:
      - kafka


volumes:
  kafka_kraft:
  mysqlvol:
